### ISSUE TITLE
Error: Glimmer keyword items with args [] can not be handled inside parent

### ISSUE THREAD

**Issue by rubycoder** [AndyObtiva/glimmer-cs-gladiator#1]
Glimmer looks fantastic!  I can't wait to give it a try.
To get an idea of what it can do, I tried running Gladiator on Windows 7 with JRuby 9.2.14.0, but I get an error while Gladiator is starting.   I get the same error on Windows 10 with JRuby 9.2.13.0.  Thanks for any advice.

```
c:\>gladiator -J-Xmx3000M
The signal INT is in use by the JVM and will not work correctly on this platform
The signal TERM is in use by the JVM and will not work correctly on this platform
[2020-12-29 17:14:00] ERROR glimmer: Encountered an invalid keyword at this object:
[2020-12-29 17:14:00] ERROR glimmer: C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:58:in `handle': Glimmer keyword items with args [] can
not be handled inside parent #<Glimmer::SWT::ShellProxy:0x1acaf3d>! Check the validity of the code. (Glimmer::InvalidKeywordError)
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/expression_handler.rb:52:in `handle'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:169:in `interpret'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer.rb:73:in `method_missing'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/lib/views/glimmer/gladiator.rb:234:in `block in Gladiator'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/parent_expression.rb:29:in `add_content'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:190:in `add_content'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:175:in `block in interpret_expression'
        from org/jruby/RubyKernel.java:1897:in `tap'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:174:in `interpret_expression'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:62:in `block in shell'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/lib/views/glimmer/gladiator.rb:194:in `block in Gladiator'
        from org/jruby/RubyBasicObject.java:2694:in `instance_exec'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/ui/custom_widget.rb:155:in `initialize'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/ui/custom_shell.rb:31:in `initialize'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/dsl/swt/custom_widget_expression.rb:49:in `interpret'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:174:in `interpret_expression'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:170:in `interpret'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer.rb:73:in `method_missing'
        from C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/bin/gladiator_runner.rb:6:in `<main>'

NoMethodError: undefined method `items' for nil:NilClass
        method_missing at org/jruby/RubyBasicObject.java:1715
        method_missing at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer.rb:78
             Gladiator at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/lib/views/glimmer/gladiator.rb:234
           add_content at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/parent_expression.rb:29
           add_content at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:190
  interpret_expression at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:175
                   tap at org/jruby/RubyKernel.java:1897
  interpret_expression at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:174
                 shell at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:62
             Gladiator at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/lib/views/glimmer/gladiator.rb:194
         instance_exec at org/jruby/RubyBasicObject.java:2694
            initialize at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/ui/custom_widget.rb:155
            initialize at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/ui/custom_shell.rb:31
             interpret at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.10.8/lib/glimmer/dsl/swt/custom_widget_expression.rb:49
  interpret_expression at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:174
             interpret at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer/dsl/engine.rb:170
        method_missing at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-1.0.6/lib/glimmer.rb:73
                <main> at C:/Ruby/jruby-9.2.14.0/lib/ruby/gems/shared/gems/glimmer-cs-gladiator-0.6.3/bin/gladiator_runner.rb:6

c:\>jgem list                                          
                                                     
*** LOCAL GEMS ***                                   
                                                     
array_include_methods (1.0.4)                        
awesome_print (1.8.0)                                
clipboard (1.3.5)                                    
cmath (default: 1.0.0)                               
csv (default: 1.0.0)                                 
did_you_mean (1.2.1)                                 
facets (3.1.0)                                       
fileutils (default: 1.1.0)                           
filewatcher (1.1.1)                                  
git-glimmer (1.7.0)                                  
glimmer (1.0.6)                                      
glimmer-cs-gladiator (0.6.3)                         
glimmer-dsl-swt (4.17.10.8)                          
ipaddr (default: 1.2.0)                              
jar-dependencies (default: 0.4.0)                    
jruby-openssl (default: 0.10.5 java)                 
jruby-readline (default: 1.3.7 java)                 
jruby-win32ole (0.8.5)                               
json (default: 2.2.0 java)                           
little-plugger (1.1.4)                               
logging (2.3.0)                                      
method_source (1.0.0)                                
minitest (5.10.3)                                    
multi_json (1.15.0)                                  
nested_inherited_jruby_include_package (0.3.0)       
net-telnet (0.1.1)                                   
optimist (3.0.1)                                     
os (1.1.1)                                           
pastel (0.8.0)                                       
power_assert (1.1.3)                                 
psych (default: 3.2.0 java)                          
puts_debuggerer (0.11.0)                             
rake (12.3.2)                                        
rake-ant (default: 1.0.4)                            
rake-tui (0.2.3)                                     
rchardet (1.8.0)                                     
rdoc (default: 6.1.2)                                
rouge (3.26.0)                                       
ruby-debug-base (0.10.7 java)                        
ruby-debug-ide (0.7.2)                               
scanf (default: 1.0.0)                               
super_module (1.4.1)                                 
test-unit (3.2.8)                                    
text-table (1.2.4)                                   
tty-color (0.6.0)                                    
tty-cursor (0.7.1)                                   
tty-prompt (0.23.0)                                  
tty-reader (0.9.0)                                   
tty-screen (0.8.1)                                   
webrick (default: 1.6.1)                             
wisper (2.0.1)                                       
xmlrpc (0.3.0)            

c:\>jruby -v
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 Java HotSpot(TM) 64-Bit Server VM 25.261-b12 on 1.8.0_261-b12 +jit [mswin32-x86_64]   
```

**Comment by AndyObtiva** [comment]
Thanks for the kind words regarding Glimmer. 

Sorry about the issue. I added new code in the latest release that was related to the Mac and forgot to OS-block it by Mac only.

I just fixed the issue in this release: [v0.6.4](https://rubygems.org/gems/glimmer-cs-gladiator/versions/0.6.4)

Let me know if you have any other inquiries.

Cheers.

P.S. as far as trying Glimmer, Gladiator recently supported opening a Scratchpad via CMD+SHIFT+S (CTRL+SHIFT+S on Windows) and pasting Glimmer GUI DSL code in directly, and then running via CMD+SHIFT+R (CTRL+SHIFT+R on Windows), like this code example:

```ruby
shell {
  text 'Hi'
  label {
    text 'Hello'
    font height: 60
  }
}.open
```
